### ISSUE TITLE
Day 5: Comparing char and char::ToUppercase

### ISSUE THREAD

**Issue by bas-ie** [BurntSushi/advent-of-code#11]
Ok. This is going to be one of those issues that I'll look back on and be embarrassed about, I can just feel it. But why on earth can't I do this?

```rust
fn react (input: &str) -> String {
    let polymer: Vec<char> = input.chars().collect();
    let mut stable: Vec<char> = vec![];

    let mut c = polymer.iter().peekable();
    
    match c.next() {
        Some(first) => {
            match c.peek() {
                Some(second) => {
                    if first.is_uppercase()
                        && second.is_lowercase()
                        && *first != second.to_uppercase() {
                        stable.push(*first);
                        stable.push(**second);
                    }
                },
                None => stable.push(*first),
            }
        },
        None => {},
    }

    stable.into_iter().collect()
}
```
Hopefully it's obvious this isn't my final logic :blush: I'm just playing with iterators to try to understand more about them. But because `std::char::ToUppercase` doesn't implement `PartialEq` for `char`, I can't compare the two. What's the correct approach for checking a `char` against its uppercase equivalent?

**Comment by bas-ie** [comment]
Answering my own question: it returns an iterator, which I guess I knew, and you can get at the value with:
```rust
second.to_uppercase().next().unwrap()
```
I suppose this is one of those 'reasonable' `unwrap` occasions, given that I know exactly what's in the input. Or just use `.to_ascii_uppercase()`.

**Comment by BurntSushi** [comment]
@richchurcher Right, yeah, your solution works because you're assuming ASCII. With that said, if you're assuming ASCII, then you can also just iterate over the raw bytes instead of dealing with `char`. If you do want to handle Unicode, then things get trickier since the uppercase equivalent of codepoints like `ß` is `SS`.

**Comment by bas-ie** [comment]
Thanks!
