### ISSUE TITLE
Day 5: advancing or 'skipping' an iterator

### ISSUE THREAD

**Issue by bas-ie** [BurntSushi/advent-of-code#12]
So I was playing with peekable iterators today. I noticed that I wanted to be able to advance an iterator to skip one char inside a `while let`, which I suspect isn't possible. Is there an idiomatic equivalent? This just seems ugly:

```rust
fn reaction (polymer: &Vec<char>) -> Vec<char> {
    let mut stable: Vec<char> = vec![];

    let mut c = polymer.iter().peekable();
    let mut skip_char = false;

    while let Some(first) = c.next() {
        if skip_char {
            skip_char = false;
            continue;
        }

        match c.peek() {
            Some(second) => {
                if will_react(first, second) {
                    skip_char = true;
                } else {
                    stable.push(*first);
                }
            },
            None => stable.push(*first),
        }
    }

    stable
}
```
https://github.com/richchurcher/advent-of-code-2018/blob/master/src/day5.rs

**Comment by BurntSushi** [comment]
That looks fine to me. What do you think is ugly about it?

**Comment by bas-ie** [comment]
Mmm, maybe you're right. I guess I was hoping I could somehow call `c.skip()` from within the loop to artificially advance it without caring about the value, and without having to rely on a variable external to the loop. But this works too :smile:
