### ISSUE TITLE
Why read from stdin ?

### ISSUE THREAD

**Issue by flofriday** [BurntSushi/advent-of-code#14]
Sorry if this is a dumb question, but why do you read from stdin instead of opening and reading the input file directly within the rust code?

Still, thank you for making your solutions public.

**Comment by BurntSushi** [comment]
Mostly because many of the puzzles have test inputs, and it's convenient to be able to change which file you give to the program instead of hard-coding a path. I could have accepted a file path as an argument to the program, but that's more work than just reading from stdin.

**Comment by flofriday** [comment]
I totally forgot the test inputs.

Sure it would be more work, but maybe it would be more "complete"? 
I don't know.

Again thank you for all the great work you are doing and being so much involved in the rust community.

**Comment by BurntSushi** [comment]
Thanks for the kind words. I don't think I know what it means to be complete in this context. I don't really see anything wrong or incomplete about reading from stdin.
