### ISSUE TITLE
Solution for day 20 seems to be wrong

### ISSUE THREAD

**Issue by smarnach** [BurntSushi/advent-of-code#15]
The solutions your code prints for day 20 seem to be wrong. So how did you make it to the second part without solving the first one? :smiley: 

I think there are two major problems with the approach of the solution. For one, the code doesn't seem to build the product set of concatenated alternations, e.g. `(N|S)(E|W)` isn't expanded to `NE`, `NW`, `SE`, `SW`. And second, the code only follows paths given in the regular expression, while the shortest way to the most distant room might be a different one, e.g. for the regex `NESW`, the code would evaluate that the most distant room is three doors a way, while the correct answer is only two doors.

Assuming that I haven't missed anything, it may be helpful for other people looking at the code to add a comment that the solution does not work – I at least was pretty confused when trying to figure out how the solution works, since I assumed it produces the correct solution.

**Comment by BurntSushi** [comment]
> So how did you make it to the second part without solving the first one?

Because my program outputs the expected answer for my input? Did you try running the program?

```
$ cargo run --release < input/input.txt
largest number of doors: 4050
pass through at least 1000 doors: 8564
```

Screenshot of AoC answers: https://i.imgur.com/9SbM58M.png

But yes, the solution does look wrong. I would have assumed it to be correct too. :-)

**Comment by BurntSushi** [comment]
> So how did you make it to the second part without solving the first one?

Because my program outputs the expected answer for my input? Did you try running the program?

```
$ cargo run --release < input/input.txt
largest number of doors: 4050
pass through at least 1000 doors: 8564
```

Screenshot of AoC answers: https://i.imgur.com/9SbM58M.png

But yes, the solution does look wrong. I would have assumed it to be correct too. :-)

**Comment by smarnach** [comment]
Hmm, that's surprising. My solution prints these answers:

    Distance to most remote room: 3810
    Number of rooms more than 1000 doors away: 8615

And they are accepted by the AoC website as well:

![image](https://user-images.githubusercontent.com/249196/50725892-824b6a80-1105-11e9-87ce-6d1118fdd9f6.png)

I still believe that my solution is correct, since it seems to be correct in the simple cases I can verify.

**Comment by smarnach** [comment]
Oh, I did not realize the puzzle input is randomized, which is why assumed the answers were wrong. But you are right, for your input your code produces the correct solution. The puzzle input apparently never concatenates alternations in a way that it becomes relevant to process the whole product, and the resulting maze does not contain any cycles, so both of my points above are not relevant for the particular kind of input.

Anyway, thanks for publishing your code – I'm enjoying comparing it to my solutions. :)
