### ISSUE TITLE
AOC01: Using std::io::Result instead?

### ISSUE THREAD

**Issue by satiani** [BurntSushi/advent-of-code#16]
Thanks for generously publishing your code, @BurntSushi, it's really helping me learn idiomatic Rust.

In your solution for Day 1, you specify a type alias (is that the right term?) like this:

```
type Result<T> = ::std::result::Result<T, Box<::std::error::Error>>;
```

Which seems awfully similar to the Result that gets provided by `std::io::Result`, which looks like this:

```
pub type Result<T> = result::Result<T, Error>;
```

My question is that why not just do `use std::io::Result` instead of rolling your own type? I've used that Result in my own solution, and it seemed to work.

**Comment by BurntSushi** [comment]
Because Box<Error> works with anything that implements the Error trait. For
example, if you have a call to parse, then that doesn't return an
io::Error, which is what the io::Result type alias uses.

**Comment by satiani** [comment]
Got it, thanks for the response!

**Comment by n8henrie** [comment]
@satiani -- You may find [this post (by the repo owner)](https://blog.burntsushi.net/rust-error-handling/) enlightening, I know I did.
