### ISSUE TITLE
::std?

### ISSUE THREAD

**Issue by andysalerno** [BurntSushi/advent-of-code#2]
Since rust no longer requires `::create_name` as of 1.30.0, is it still idiomatic to use it for `::std` like in this repo?

I guess it's still the most unambiguous form?  I'm asking as a near-beginner in Rust.

**Comment by BurntSushi** [comment]
Sure, ya, you might be right! It can take a while for new language features to become idioms though. I don't often write code that specifically targets the latest version of stable Rust, so I'm unlikely to change immediately. But I'll look into this for future AoC solutions! Thanks!
