### ISSUE TITLE
When to use vec! instead of Vec::new()?

### ISSUE THREAD

**Issue by arclabs561** [BurntSushi/advent-of-code#5]
https://github.com/BurntSushi/advent-of-code/blob/d5e3fe31ccc4b260e7377cb1d88ba78438840655/aoc03/src/main.rs#L26

**Comment by BurntSushi** [comment]
I think I pretty much always use `vec![]`. I can't think of any specific instance where I'd want to use `Vec::new`, unless I wanted to use it as a function value. e.g., if you have

```rust
fn build_a_vec(build: impl Fn() -> Vec<i32>) {
    let vector = build();
    // do something with vector
}

fn main() {
    build_a_vec(Vec::new);
}
```

But even then, that's not code I can remember writing.

I believe the choice between `vec![]` and `Vec::new` is almost entirely stylistic. The former is more flexible, so it tends to be what folks use.

Note that in the code you referenced, I did include the type, `Vec<Claim>`, which I believe is optional in that context. I include the type sometimes to make the code clearer. It's a judgment call. :-)
