### ISSUE TITLE
aoc10: 80x80 canvas?

### ISSUE THREAD

**Issue by dnwe** [BurntSushi/advent-of-code#7]
I was wondering how you determined from the [instructions](https://adventofcode.com/2018/day/10) that the points would all fit within an 80x80 canvas when the message was being displayed?

https://github.com/BurntSushi/advent-of-code/blob/6285296770ee7f47003cf9b55a70e875f331000e/aoc10/src/main.rs#L29-L37

**Comment by BurntSushi** [comment]
See here: https://github.com/BurntSushi/advent-of-code/commit/bbdce2175ab49494319a8c6af8117806d71ba4cf#r31621663

**Comment by dnwe** [comment]
thanks!
