### ISSUE TITLE
Day 8: HashMap.copy is expensive

### ISSUE THREAD

**Issue by fabienjuif** [BurntSushi/advent-of-code#8]
Hi @BurntSushi 👋 

I think I struggle with borrow checker and copying my collections.
Right know, everytime I had a "borrow check" hit, I just cloned my collection (eg: `my_map.clone()`).
But with day8 this is so expensive!

My programs runs in more than 1sec, where yours runs in < 0.01s! 😨 

For me, the big problem is with this code:
```rust
// ...
    let mut nodes = HashMap::<i32, Node>::new();

// ... loop {
                let ref_nodes = nodes.clone();
                nodes.entry(current_id)
                    .and_modify(|node| node.add_metadata(value, ref_nodes));
// ... }
```

That reference this:
```rust
#[derive(Debug, Clone)]
struct Node {
    id: i32,
    parent: Option<i32>,
    value: i32,
    childs_count: i32,
    childs: Vec<i32>,
    metadatas_count: i32,
    metadatas: Vec<i32>,
}

impl Node {
    fn has_metadatas (&self) -> bool {
        self.metadatas_count == self.metadatas.len() as i32
    }

    fn add_metadata (&mut self, metadata: i32, nodes: HashMap<i32, Node>) {
        self.metadatas.push(metadata);

        if self.has_metadatas() {
            self.value = self.metadatas.iter().fold(
                0,
                |acc, curr| {
                    if self.childs_count == 0 {
                        return acc + curr;
                    }
                    return acc + match self.childs.get(*curr as usize - 1) {
                        None => 0,
                        Some(child_id) => nodes.get(&child_id).unwrap().clone().value,
                    }
                }
            );
        }
    }
}
```

As you can see:
  1. I copy the HashMap
  2. I add a new metadata to the node vector (mutating)
  3. If all metadatas are present for this node, I process the value
  4. I then need the global HashMap to retrieve children node values (reading)

More over I do this a lot of time (but, there this is my algorithm that is ... shitty, so don't worry about this :) )

Here is my question (finally!): How do you handle that!
I thank I understood what you said here: https://github.com/BurntSushi/advent-of-code/issues/6 but I still struggle :(

Tank you!

PR containing my code is here: https://github.com/fabienjuif/advent-of-code-2018/pull/2/files
Source code is here: https://github.com/fabienjuif/advent-of-code-2018/tree/day7/day8

**Comment by fabienjuif** [comment]
Ok:

```
➜  day8 git:(day7) ✗ time ./target/release/day8
part1: 44893
part2: 27433
./target/release/day8  0.01s user 0.00s system 82% cpu 0.013 total
➜  day8 git:(day7) ✗
```

1. Update to Rust 2018 edition
2. Cut the previous code like this:
```rust
                nodes.entry(current_id)
                    .and_modify(|node| node.add_metadata(value));

                let current_node = nodes.get(&current_id).unwrap();
                if current_node.has_metadatas() {
                    let value = current_node.get_value(&nodes);
                    nodes.entry(current_id)
                        .and_modify(|node| node.value = value);
                }
```

With:
```rust
impl Node {
    fn has_metadatas (&self) -> bool {
        self.metadatas_count == self.metadatas.len() as i32
    }

    fn add_metadata (&mut self, metadata: i32) {
        self.metadatas.push(metadata);
    }

    fn get_value (&self, nodes: &HashMap<i32, Node>) -> i32 {
        self.metadatas.iter().fold(
            0,
            |acc, curr| {
                if self.childs_count == 0 {
                    return acc + curr;
                }
                return acc + match self.childs.get(*curr as usize - 1) {
                    None => 0,
                    Some(child_id) => nodes.get(&child_id).unwrap().clone().value,
                }
            }
        )
    }
}
```

But it still doesn't seem quite right

**Comment by BurntSushi** [comment]
I don't think I quite have the time to fix that code. The problem is that you've specifically organized your code such that an element inside your hash map can be mutated, but the mutation you've defined *also* requires access to the original hashmap. The only way you can achieve something like that is with interior mutability, which I don't think would be wise here. Instead, you should reorganize your code such that you don't simultaneously require immutable and mutable access to the same hashmap.

One other thing you could do is remove the node from the hashmap, do your mutation, and then re-add it:

```rust
                    let mut node = nodes.remove(&current_id).unwrap();
                    node.add_metadata(value, &nodes);
                    nodes.insert(current_id, node);
```

**Comment by fabienjuif** [comment]
Thank you for the time you already take/took 👍 
Thanks for the advices.

**Comment by kcaffrey** [comment]
@fabienjuif I’m also fairly new to Rust, so my code may not be idiomatic, but if you want some more perspectives on ways to solve this problem you can check out my solutions: https://github.com/kcaffrey/aoc-rs/blob/master/src/day8.rs

I coded two variations. One builds the tree explicitly (like BurntSushi) while the other computes everything in-place. Note that my explicit tree solution attempted to avoid copies and allocations, so I stored a reference to the original input slice (that’s why my Node has a lifetime).
