### ISSUE TITLE
Walk through your thought process for day 10

### ISSUE THREAD

**Issue by mklein994** [BurntSushi/advent-of-code#9]
First of all, thank you for taking the time to complete these puzzles; it shows how someone with experience in Rust would approach these problems, given that we all get the same instructions. That being said, I struggle with grasping how one would reach this point, since all I see is the final result.

What's your process to developing a solution? Do you just sit down and write the code like this with an idea already in mind of how to solve it, or does it take a few tries? If you ran into problems with your first attempt, how did you fix those? What gave you the idea only drawing grids smaller than (or equal to) 80 x 80? I also find it interesting that you adjust the bounds as you keep drawing the grid.

Is this code "good enough", or do you feel that you could improve it?

Thanks again for doing this.

Edit: I just saw issue #7.

**Comment by BurntSushi** [comment]
Thanks for the questions! I'll do my best to answer them, but these are tough questions. :-) In particular, I'm not sure whether you're asking about the puzzle solving aspect of doing these problems, or if you're looking for a more Rust specific answer to them.

> What's your process to developing a solution? Do you just sit down and write the code like this with an idea already in mind of how to solve it, or does it take a few tries?

I've found the specification for the problems in AoC to be pretty good. At least, it's good enough for me to be able to see how to solve the problem from beginning to end after a careful read. I don't think I've had to completely change how I approached a problem so far. With that said, my solutions have been pretty uninspiring and not particularly clever. That is, I've chosen the brute force approach in almost every case. I'm not particularly good at puzzles. :-)

If you're new to Rust, then the language itself may be tripping you up. That is, you might need a few tries to figure out how best to structure your code. I personally don't have that problem. I've been writing Rust long enough that I can intuitive navigate that space without really thinking explicitly about it. If I remember back to when I was learning Rust, and if I had attempted the AoC solutions then, then I absolutely would have struggled more. I probably would have had at least several false starts.

> If you ran into problems with your first attempt, how did you fix those?

I think it's hard to speak generally about this.

> What gave you the idea only drawing grids smaller than (or equal to) 80 x 80?

Hah. Well, I tried without that restriction first, and the program ended up using enough memory to get killed IIRC. At that point, I thought about how I was supposed to detect letters in a grid that large. The only thing I could think of would be to actually try to detect the letters in the grid without materializing the full grid, and that sounded hard and out of scope for a one day AoC problem. So I just figured that the answer is probably in a grid that's small enough to feasibly print and read. So I tried a few width/height configurations and that was that.

Frankly, I consider the above kind of a cheat. But I've got to be practical. I can only spend a small amount of time on each puzzle. It's also very likely that I'm just not clever enough to solve it the intended way. That is, can you come up with a solution that works even if the grid never gets small enough to print or fit into memory? Maybe there's a simple solution. I don't know. But if not, I just settle for something that's more restricted in scope to specific kinds of inputs.

> I also find it interesting that you adjust the bounds as you keep drawing the grid.

I think you have to figure out the bounds of the grid somehow? I suppose I could have went with something like a `BTreeSet<Point>` and used the inherent ordering of btrees to handle it. But yeah, sure, there are probably other approaches.

> Is this code "good enough", or do you feel that you could improve it?

I would say that almost all of my AoC solutions are, approximately, shitty first drafts of what I would write. I don't really go and refactor the code after I've solved both parts. This may make them somewhat less useful as educational tools in that there are things that could be done better in terms of the computational approach to solving the puzzle, but I do at least feel somewhat confident that my use of Rust itself is fairly solid. At the end of the day, I have to balance costs. :-) The key constraint I set for myself was that programs shouldn't panic given any user input. This is a key forcing function that drives the structure of the code, and definitely makes it longer that most other solutions you see to these puzzles. But that's kind of the point. In real programs, you don't panic on bad user input, so it's important to show how to actually achieve that.

**Comment by mklein994** [comment]
Thanks for answering those questions. You made some good points there. I'm relatively new to Rust in general, so I guess that's tripping me up, the same way someone learning a new language would when trying to find the right word for something.

**Comment by fabienjuif** [comment]
Hi @mklein994 @BurntSushi !

I don't know if this is relevant but here is my solution, where I don't use a 80x80 fix grid: https://github.com/fabienjuif/advent-of-code-2018/blob/master/day10/src/main.rs 

The idea was "if the letter should align themself at some point, then the grid will be the smallest at this iteration".

So when my grid begins to grow, it means the previous iteration was the good one!
